name: Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Create application.properties for Dialog and Game services from GitHub.secrets
      run: |
        touch Dialog/src/main/resources/application.properties
        echo "server.port=9092" >> Dialog/src/main/resources/application.properties
        echo "spring.jackson.deserialization.fail-on-unknown-properties=false" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.hostname=${{ secrets.RABBITMQ_HOSTNAME }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.username=${{ secrets.RABBITMQ_USERNAME }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.password=${{ secrets.RABBITMQ_PASSWORD }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.virtualHost=${{ secrets.RABBITMQ_VIRTUALHOST }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.exchange=${{ secrets.RABBITMQ_EXCHANGE }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.queue.dialog=${{ secrets.RABBITMQ_QUEUE_DIALOG }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.routingKey.dialog=${{ secrets.RABBITMQ_ROUTINGKEY_DIALOG }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.queue.game=${{ secrets.RABBITMQ_QUEUE_GAME }}" >> Dialog/src/main/resources/application.properties
        echo "rabbitmq.routingKey.game=${{ secrets.RABBITMQ_ROUTINGKEY_GAME }}" >> Dialog/src/main/resources/application.properties
        
        touch Game/src/main/resources/application.properties
        echo "server.port=9093" >> Game/src/main/resources/application.properties
        echo "spring.jackson.deserialization.fail-on-unknown-properties=false" >> Game/src/main/resources/application.properties
        echo "rabbitmq.hostname=${{ secrets.RABBITMQ_HOSTNAME }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.username=${{ secrets.RABBITMQ_USERNAME }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.password=${{ secrets.RABBITMQ_PASSWORD }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.virtualHost=${{ secrets.RABBITMQ_VIRTUALHOST }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.exchange=${{ secrets.RABBITMQ_EXCHANGE }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.queue.dialog=${{ secrets.RABBITMQ_QUEUE_DIALOG }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.routingKey.dialog=${{ secrets.RABBITMQ_ROUTINGKEY_DIALOG }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.queue.game=${{ secrets.RABBITMQ_QUEUE_GAME }}" >> Game/src/main/resources/application.properties
        echo "rabbitmq.routingKey.game=${{ secrets.RABBITMQ_ROUTINGKEY_GAME }}" >> Game/src/main/resources/application.properties
    - name: Run tests
      run: | 
        mvn mvn spring-boot:run -pl PointsCalculator
        mvn clean test
